name = "cloudflare-worker-boilerplate"
main = "src/index.ts"
compatibility_date = "2023-03-10"

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.