name = "cloudflare-worker-boilerplate"
main = "src/index.ts"
compatibility_date = "2023-03-10"

[[d1_databases]]
binding = "DB"
database_name = "USER_DATABASE"
database_id = "11e0ea22-7c4e-4b82-af94-60432028e446"

[triggers]
crons = ["*/15 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.